---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
  persistentVolumeReclaimPolicy: Recycle
