apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: jberkhahn/guestbooktest
        ports:
        - name: http-server
          containerPort: 3000
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: "pub-redis-17681.dal-05.1.sl.garantiadata.com"
        - name: REDIS_MASTER_SERVICE_PORT
          value: "17681"
        - name: REDIS_MASTER_SERVICE_PASSWORD
          value: "zA15N4yvtm2tZuIIGwH8bULQWgYbeW2X"
        - name: REDIS_MASTER_PORT
          value: "foobar"
